kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "mario.fullname" . }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "mario.fullname" . }}-service
    gateway: multi-cluster-gateway 
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - kind: Gateway
      name: {{ include "mario.fullname" . }}-gateway
      namespace: mario
  rules:
    - backendRefs:
        - group: net.gke.io
          kind: ServiceImport
          name: {{ include "mario.fullname" . }}-service
          port: 80