name: Sync Branches

on:
  # Trigger when changes are pushed to prod
  push:
    branches: 
      - prod

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: dev
          token: ${{ secrets.GITHUB_TOKEN }}