name: Sync Branches

on:
  # Trigger when changes are pushed to prod
  push:
    branches: [ "prod" ]

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync branches
        uses: TreTuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          FROM_BRANCH: prod
          TO_BRANCH: staging
